SELECT * FROM Workers;
SELECT * FROM MATOT;
SELECT * FROM [object];
SELECT * FROM USEMAT;

ALTER TABLE [object]									
ADD CONSTRAINT FOREMAN_OBJECT_FK					
foreign key (FOREMAN) REFERENCES Workers(FOREMAN);

ALTER TABLE [USEMAT]									
ADD CONSTRAINT USEMAT_OBJECT_FK					
foreign key (IDOBJ) REFERENCES [object](IDOBJ);

ALTER TABLE [USEMAT]									
ADD CONSTRAINT USEMAT_MATOT_FK					
foreign key (IDMAT) REFERENCES MATOT(IDMAT);